[project]
name = "drone-detection"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "jupyterlab>=4.4.10",
    "matplotlib>=3.10.7",
    "pandas>=2.3.3",
    "ultralytics>=8.3.226",
]
